alias jl='~/jupyter_env/.venv/bin/jupyter-lab --notebook-dir= ~/Vorlesungen/NLP/Notebooks/'
alias suspend='systemctl suspend'
alias open='xdg-open'
alias pint='./vendor/bin/pint'
alias stan='./vendor/bin/phpstan'
alias pest='./vendor/bin/pest'
alias rector='./vendor/bin/rector'
alias sail='./vendor/bin/sail'
alias db='lazysql "file:database/database.sqlite?loc=auto"'
